In [1]:
from IPython.display import HTML
HTML('<iframe src="iris.txt" width="800px"/>')

# Use SckKitLearn
## Some Terminology
- Feature
- Target

In [2]:
from sklearn.datasets import load_iris # this is typical convention -- you load specific modules/functions not the whole lib
iris_data = load_iris()
type(iris_data) # it's a Bunch object

sklearn.utils.Bunch

In [24]:
print(iris_data.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [3]:
print(iris_data.data)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [4]:
iris_data.feature_names # aka column names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [5]:
iris_data.target_names # the three different species of Iris in the dataset

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [6]:
iris_data.target # this is what going to be predicted. the learning algorithm should return a o (for setosa), a 1 (for veriscolor) or a 2 (for virginica)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

Two Types of Supervised Learning: Classification and Regression

# Requirements for working with data in scikit-learn
- Features and response are separate objects
- Features and response should be numeric
- Features and response should be NumPy arrays
- Features and response should have specific shapes

In [7]:
# feature object is... 
print(type(iris_data.data))

# response object is...
print(type(iris_data.target))

#...they're 1) seperate objects, 2) contain only numeric values and 3) their object type is numpy.ndarray

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


The "shape" of the data we're going to pass in is the number of observations (rows) and the number of features (columns)
In the case of the Iris Data Set, there are 150 observations each containing the 4 features

In [8]:
print(iris_data.data.shape) # the shape of the input data is 150 observations, each with 4 features...

(150, 4)


The shape of the response object is the total number of observations

In [9]:
print(iris_data.target.shape) # the shape of the target response is 150

(150,)


In [10]:
# By convention...
# feature data stored in X (upper)
X = iris_data.data
# response data stored in y 
y = iris_data.target


# Watch KNN Classification at 3:44

In [11]:
from sklearn.datasets import load_iris

iris = load_iris()

X = iris.data
y = iris.target

In [12]:
print(X.shape)
print(y.shape)

(150, 4)
(150,)


# Scikit-learn 4-steps

In [13]:
# STEP ONE
from sklearn.neighbors import KNeighborsClassifier

# STEP TWO
# instanciate the model or "estimator" in scikit-learn terms
knn = KNeighborsClassifier(n_neighbors=1) # the K value
print(knn)

# STEP THREE
# fit the model with data
knn.fit(X,y)

# STEP FOUR
# make predictions
response = knn.predict([[3,5,4,2]])

print(response) # it prints out 2 - it's predicting that features given belong to a "2" in the data set
# setosa = 0
# versicolor 1
# virginica = 2'

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')
[2]


In [14]:
observations = [[3,5,4,2],[5,4,3,2]]
response = knn.predict(observations)
print(response)

[2 1]


In [15]:
# Now try it with a different value for K
knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(X,y)

response = knn.predict(observations)
print(response)

[1 1]


## Try a different algorithm...

In [16]:
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression()
# print(logreg)

logreg.fit(X, y)

response = logreg.predict(observations)
print(response)

C:\Users\HarveyPC\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\HarveyPC\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


[2 0]
